### ISSUE TITLE
Question about the \delta G evaluation

### ISSUE THREAD

**Issue by Guo-Stone** [EDAPINENUT/ppflow#6]
Dear authors,
I have a question about ADCP evaluation. In my opinion, you use ADCP for re-docking after the generation of the peptide. I think that we have to evaluate the conformation of generated peptides. But if you use ADCP for re-docking, the generated conformation will change. Do I misunderstand anything?
Or do you only use ADCP to score a generated complex conformation while keeping it unchange?
Looking forward to your response!

**Comment by EDAPINENUT** [comment]
That's true. ADCP is a flexible docking method, which will change both the conformation and the pose of the peptide. 
In previous works in target-aware molecule generation, such as TagetDiff and MolCraft, they will evaluate the docking energy under vina score, vina min, and vina dock mode. In the first, it is like the foldx energy, the second will only change the pose, while the final is like ADCP evaluation.

We use a similar protocol so that ADCP is used just like vina dock modes in SBDD tasks.

If you have any further questions, feel free to ask here.

**Comment by Guo-Stone** [comment]
Thanks for you kind response. From your paper, I know that FoldX could be used to score given a complex conformation. But if you use ADCP to re-dock the generated conformation, how can you evaluate the generated conformation after re-docking?
